#!/usr/bin/env python3
"""
Generate a {address: symbol} ROM map from Espressif ROM linker scripts.

The ESP mask ROM is fixed in silicon, so these addresses are stable across IDF/SDK
versions. Two linker-script symbol formats are supported:

    PROVIDE ( name = 0xADDR );   # weak symbols  (esp32.rom.ld, eagle.rom.addr.v6.ld)
    name = 0xADDR;               # strong symbols (esp32.rom.newlib-funcs.ld,
                                 #                 esp32.rom.libgcc.ld)

Regenerate the ESP32 ROM *code* map consumed by binaryview.setup_esp32_map (linker
scripts live in esp-idf at components/esp_rom/esp32/ld/):

    python3 parse_rom_ld.py --var esp32_rom_symbols --lo 0x40000000 --hi 0x40070000 \\
        -o esp32_rom_symbols.py \\
        esp32.rom.ld esp32.rom.newlib-funcs.ld esp32.rom.libgcc.ld

Regenerate the ESP8266 map (the original use), from eagle.rom.addr.v6.ld:

    python3 parse_rom_ld.py --var known_symbols -o known_symbols.py eagle.rom.addr.v6.ld
"""
import argparse
import re

_PROVIDE = re.compile(r'^\s*PROVIDE\s*\(\s*([A-Za-z_]\w*)\s*=\s*(0x[0-9a-fA-F]+)\s*\)\s*;')
_ASSIGN = re.compile(r'^\s*([A-Za-z_]\w*)\s*=\s*(0x[0-9a-fA-F]+)\s*;')


def parse_ld(paths, lo, hi):
    """Return {addr: name} for symbols in [lo, hi). Earlier files win on conflict."""
    syms = {}
    for path in paths:
        with open(path) as f:
            for line in f:
                m = _PROVIDE.match(line) or _ASSIGN.match(line)
                if not m:
                    continue
                name, addr = m.group(1), int(m.group(2), 16)
                if lo <= addr < hi:
                    syms.setdefault(addr, name)
    return syms


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("ld", nargs="+", help="ROM linker script(s) to parse")
    ap.add_argument("-o", "--out", required=True, help="output .py module path")
    ap.add_argument("--var", default="rom_symbols", help="dict variable name")
    ap.add_argument("--lo", type=lambda x: int(x, 0), default=0,
                    help="keep symbols with addr >= LO (default 0)")
    ap.add_argument("--hi", type=lambda x: int(x, 0), default=0xffffffff,
                    help="keep symbols with addr < HI (default 0xffffffff)")
    args = ap.parse_args()

    syms = parse_ld(args.ld, args.lo, args.hi)
    with open(args.out, "w") as f:
        f.write('"""ROM symbol map {address: name}, generated by parse_rom_ld.py.\n\n')
        f.write("Source linker scripts: %s\n" % ", ".join(args.ld))
        f.write("Address window: [%#010x, %#010x). ROM is silicon-fixed.\n\"\"\"\n\n"
                % (args.lo, args.hi))
        f.write("%s = {\n" % args.var)
        for addr in sorted(syms):
            f.write("    %#010x: %r,\n" % (addr, syms[addr]))
        f.write("}\n")
    print("wrote %d symbols to %s" % (len(syms), args.out))


if __name__ == "__main__":
    main()
